### PR TITLE
Improvements to metadata for Github

### PR DESCRIPTION
**Pull request by dkfellows**
Do we have a recommended citation for this repository?

### CODE REVIEW

**Comment by dkfellows** [comment]
Also, what license should be on this code? (Was this done when Peter was employed by us? I _think_ it was...)

**Review by Christian-B — APPROVED** [review]

**Comment by andrewgait** [comment]
> Also, what license should be on this code? (Was this done when Peter was employed by us? I _think_ it was...)

Yes this was done by Peter originally.  There's a PR in to keep it up to date with master which I guess we'll get to at some point soon - the sPyNNaker branch of that still needs a bit more work on it.

**Comment by dkfellows** [comment]
Keeping this open until we've got a license and possibly citation.

**Comment by dkfellows** [comment]
The citation isn't perfect by any means (it's really for the article they wrote) but it's what I could scrape up.

**Pull request merged**
